### PR TITLE
Update org.kde.Platform to 5.15-21.08

### PR DESCRIPTION
**Pull request by tim77**
Update to latest and greatest KDE runtime based on Freedesktop 21.08. Tested this build locally and LGTM so far.

### CODE REVIEW

**Comment by DamirPorobic** [comment]
@LyzardKing any objections?

**Comment by LyzardKing** [comment]
Looks good... I checked and many upstream kde flatpaks use the new runtime as well.
I haven't tested it yet, but I'll download it now and let you know later today

**Comment by LyzardKing** [comment]
@DamirPorobic Looks good to me. I think you can merge.
Sorry for the late reply, I've been busy with work

**Comment by DamirPorobic** [comment]
Thanks @tim77 for providing this PR and @LyzardKing for testing it.

**Pull request merged**
