### PR TITLE
Drop kde own name

### PR DESCRIPTION
**Pull request by bbhtt**
Will figure out what is needed for `Connect wayland screenshot portal` but giving access to entire KDE bus cannot be the solution.

### CODE REVIEW

**Comment by LyzardKing** [comment]
the org.kde permission is needed also for the flatpak to show the appindicator on certain desktop environments.
I haven't looked at it in a while, but I don't think there is a solution to this atm.

Let's test the version you built on multiple systems and see what happens.

**Comment by bbhtt** [comment]
It should not be required for appindicator anymore, see the commit message for references. I'll test it later.

**Comment by bbhtt** [comment]
Tested in a KDE Neon VM, seems to work

<details>
<summary> KDE </summary>

image

</details>

I don't see it used for anything else in `--log-session-bus`

**Comment by LyzardKing** [comment]
Could you test it in an xfce/mate system?
I seem to remember those being more prone to issues with displaying the icon in the appindicator.

**Comment by bbhtt** [comment]
I can do it later today or tomorrow.

**Comment by bbhtt** [comment]
Tested, seems to work:

<details>
<summary> XFCE </summary>

image

</details>

**Comment by bbhtt** [comment]
FYI since issues are closed here, both `org.kde.*` and `org.freedesktop.portal.*` will soon be blocked in the linter.

See https://github.com/flathub-infra/flatpak-builder-lint/issues/178 for the second one. This is a heads up to that.

**Comment by DamirPorobic** [comment]
Sorry, forgot about this PR

**Pull request merged**
